#!/usr/bin/env python3
"""Build minNotes' merged US+UK English Hunspell dictionary from two SCOWL releases.

    python3 scripts/build-merged-dictionary.py hunspell-en_US-<date>.zip hunspell-en_GB-ise-<date>.zip

SCOWL zips: https://sourceforge.net/projects/wordlist/files/speller/ (or wordlist.aspell.net/dicts/).
Both dictionaries are generated by SCOWL's make-hunspell-dict from ONE affix template, so
their .aff files are identical apart from the header comment — this script asserts that and
then unions the .dic word lists (Hunspell accepts duplicate stems carrying different flags).
Writes app/spell/en/en.aff + en.dic. Manual tool: the build never runs it.
"""
import io, sys, zipfile, re, os
if len(sys.argv) != 3:
    sys.exit(__doc__)
def read_zip(path):
    z = zipfile.ZipFile(path)
    aff = dic = readme = None
    for n in z.namelist():
        if n.endswith('.aff'): aff = z.read(n).decode('utf-8')
        elif n.endswith('.dic'): dic = z.read(n).decode('utf-8')
        elif n.lower().startswith('readme'): readme = z.read(n).decode('utf-8', 'replace')
    if aff is None or dic is None: sys.exit(f"{path}: no .aff/.dic inside")
    return aff.replace('\r\n', '\n'), dic.replace('\r\n', '\n'), readme
aff_us, dic_us, readme_us = read_zip(sys.argv[1])
aff_gb, dic_gb, readme_gb = read_zip(sys.argv[2])
strip = lambda a: [l for l in a.split('\n') if not l.startswith('#')]
if strip(aff_us) != strip(aff_gb):
    sys.exit("affix files differ beyond comments — ship en_US.aff/.dic + en_GB.dic and use add_dic() instead")
def entries(d):
    lines = d.split('\n')
    n = int(lines[0].strip()); body = [l for l in lines[1:] if l.strip()]
    assert len(body) == n, f"count header {n} != {len(body)} entries"
    return body
merged = sorted(set(entries(dic_us)) | set(entries(dic_gb)), key=lambda l: (l.split('/')[0].lower(), l))
out_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'app', 'spell', 'en')
os.makedirs(out_dir, exist_ok=True)
aff_lines = aff_us.split('\n')
aff_lines[0] = '# Affix file for the minNotes merged en_US + en_GB-ise Hunspell dictionary (SCOWL).'
with open(os.path.join(out_dir, 'en.aff'), 'w', encoding='utf-8', newline='\n') as f:
    f.write('\n'.join(aff_lines))
with open(os.path.join(out_dir, 'en.dic'), 'w', encoding='utf-8', newline='\n') as f:
    f.write(f"{len(merged)}\n" + '\n'.join(merged) + '\n')
print(f"en.dic: {len(merged)} entries (US {len(set(entries(dic_us)))}, GB {len(set(entries(dic_gb)))}); en.aff: {len(aff_lines)} lines")
m = re.search(r'COPYRIGHT, SOURCES, and CREDITS:.*', readme_us or '', re.S)
print("\n--- SCOWL copyright block (for LICENSES/SCOWL-LICENSE.txt) ---\n" + (m.group(0) if m else '(README not found)'))
